---
title: "Chapter 6 in Karolina’s thesis"
author: "Rune Haubo B Christensen @ Christensen Statistics"
date: "17 May 2018"
output: 
  html_document:
    toc: true
    toc_float: true
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

"clever-source" code from sensR package:
```{r}
# library(devtools)
# pkgpath <- "~/GitHub/sensR/sensR"
# load_all(pkgpath)

# Alternatively use:
# install.packages("devtools")
# devtools::install_github("runehaubo/sensR", ref="cbb-profile")
library(sensR)
```

## section 6.2.2 optimcbb

```{r}
# p 48:
y <- rep(4,12) #set of responses
n <- 12 #number of assessors
k <- 4 #number of replications
p0 <- 1/3 #guessing probability
#unfortunate initial values
optim(par = c(0.5, 0.5), fn = loglikcbb, y = y, k = k, p0 = p0)

#other initial values
optim(par = c(0.4, 0.4), fn = loglikcbb, y = y, k = k, p0 = p0)
```

```{r}
# p49:
#invalid initial values
optimcbb(y, k, p0, init = c(1,0))

#unfortunate initial values
optimcbb(y, k, p0, init = c(0.5,0.5))
```

## section 6.2.3 plotcbb

```{r}
# p50
y1 <- c(2,2,3,3,4,4,4,4,4,4,4,5,6,10,11) #set of responses 
k1 <- 12 #number of replications
p0 <- 1/3 #guessing probability
#plot the likelihood region
(example1 <- plotcbb(y1, k1, p0))

#check if the point is inside of the likelihood region
loglikcbb(c(0.12, 0.46), y1, k1, p0) < example1$loglik.bound

#check if the point is inside of the likelihood region
loglikcbb(c(0.12, 0.12), y1, k1, p0) < example1$loglik.bound
```

## section 6.2.4 profilecbb

```{r}
# p52
y1 <- c(2,2,3,3,4,4,4,4,4,4,4,5,6,10,11) #set of responses 
k1 <- 12 #number of replication
p0 <- 1/3 #guessing probability
#plot profile likelihood
profilecbb(y1, k1, p0)
```

## Session info

Session Info for potential debug'ing:
```{r}
sessionInfo()
```

